version: "3.9"

services:
  # elsa-backend:
  #   build:
  #     context: ./elsa-backend
  #   container_name: elsa-backend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./elsa-backend:/app
  #     - /app/node_modules
  #   env_file:
  #     - .env
  #   depends_on:
  #     - database
  #   networks:
  #     - quiz-network

  database:
    image: postgres:17-alpine
    container_name: postgres-db
    restart: always
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - quiz-network

volumes:
  db_data:

networks:
  quiz-network:
    driver: bridge
